### ISSUE TITLE
Amazon ECHO devices Not Reporting Correctly

### ISSUE THREAD

**Issue by danowitz** [IndigoDomotics/alexa-hue-bridge#13]
I installed the new 3.0.23 version and to give the echo dot device type a type.  It seems that it does not correctly output the device that actually responded to the request.  It seems to use the same device in the logs.

Thanks
Joel

**Comment by autolog** [comment]
I am not sure what you mean exactly? What is the log message?

**Comment by danowitz** [comment]
Sure sorry for not being clear.  I have multiple echo dot devices through the house. When I tell alexa to execute a command from the kitchen it shows this in the log file.

`Alexa-Hue Bridge                Request received from 'Garage Alexa 1':42831: Setting brightness of Alexa device "Kitchen Lights" to 25`

The message says "received from 'Garage Alexa 1', it should have said, 'Kitchen Alexa'.

**Comment by autolog** [comment]
Actually, it shouldn't. :)

The reason for expanding the log message with more detail is to highlight the fact that when Alexa issues a command to Indigo, it doesn't necessarily use the Echo device where the request was made to send the response back. So you make a request from the kitchen and Alexa sends the response to Indigo via the garage Echo. It is useful to know this because if you have issued a command to Alexa in the Kitchen and got a reply from Alexa saying the device is not responding, then it is a good bet to go to (in this example) the garage Echo and issue the command and then all the other Echos will start working again. Don't ask me why, it just seems to work that way. :)

**Comment by danowitz** [comment]
Well, good to know.  I was hoping that we had data that would help provide context aware alexa calls and could automatically know from which room a command was made. Thanks for clarifying!
